### ISSUE TITLE
stunnel should run unprivileged

### ISSUE THREAD

**Issue by slingamn** [darwin-network/slash#10]
Use the `setuid` and `setgid` config lines; make sure it can still read the right certificates and connect to the right UNIX domain socket, even after SIGHUP.

**Comment by eklitzke** [comment]
Are you really running stunnel as root?

**Comment by slingamn** [comment]
That's correct.

Really what should happen here is that stunnel upstream should add support for seccomp-bpf; that way, the daemon's zygote can read arbitrary certificates and connect to arbitrary UNIX domain sockets, but the processes that actually serve traffic can be restricted to read/write/poll/gettimeofday.

**Comment by eklitzke** [comment]
That's one way of looking at it. Another way of looking at is that Unix has had capabilities for non-superuser processes to read credential files since day 1.

https://linux.die.net/man/5/group

**Comment by slingamn** [comment]
The hard part is getting cooperation from Certbot (which should probably have sole control over `/etc/letsencrypt`).

Here's the totally ridiculous thing we do to make the certificates available to exim: https://github.com/darwin-network/slash/blob/000542cc675371d6c4600b8c432ed14d3db6e8ca/etc/cron.daily/install-exim-certificates

**Comment by eklitzke** [comment]
Check this out. I rescind my earlier comment about groups. The way this works on Apache, nginx, etc. is they start as root, read the certificates, and then call setuid() and setgid() to become unprivileged. stunnel supports two configuration options, setuid and setgid.

**Comment by slingamn** [comment]
Closing out the discussion, there are three viable solutions:

1. Use global `setuid` and `setgid` stunnel config options; make copies of the LE certificates owned by that uid/gid pair (because otherwise stunnel won't be able to SIGHUP reload them after dropping privileges). This is the solution that was implemented.
1. @eklitzke wrote a patch to stunnel that (when compiled to use processes instead of threads), keeps the master process running as root and does setuid/setgid only in the worker processes (comparable to the Debian nginx package)
1. Individual threads can have their own seccomp profiles, so keep the whole process running as root, but sandbox the worker threads.
