### ISSUE TITLE
submit "request to remove email sending limitations"

### ISSUE THREAD

**Issue by slingamn** [darwin-network/slash#3]
Our difficulties connecting on port 25 are likely explained by this:

https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/

Suggested use case description: (a) our app needs to be able to send account confirmation emails (b) we want to receive e-mail directed to admin@ and webmaster@

**Comment by edmund-huber** [comment]
I assigned an EIP to the EC2 instance, per their recommendation.

I submitted the request, I'll update when I get a response.

**Comment by edmund-huber** [comment]
`We've reviewed and approved your request for the removal of the EC2 e-mail sending limitations on your Amazon Web Services account. There are no longer limitations on your account for any IPs and instances under your account. If you requested removal of e-mail sending limits on Amazon Elastic IPs, they've also been removed.`  gtg?

**Comment by slingamn** [comment]
lgtm:

````
$ telnet irc.darwin.network 25
Trying 35.171.127.21...
Connected to darwin.network.
Escape character is '^]'.
220 irc.darwin.network ESMTP Exim 4.86_2 Ubuntu Thu, 15 Feb 2018 20:05:50 +0000
EHLO darwin.network
250-irc.darwin.network Hello [redacted] [[redacted]]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-STARTTLS
250-PRDR
250 HELP
MAIL FROM:<admin@darwin.network>
250 OK
RCPT TO:<majordomo@vger.kernel.org>
550 relay not permitted
QUIT
221 irc.darwin.network closing connection
Connection closed by foreign host.
````

**Comment by Madhu-aa** [comment]
> `We've reviewed and approved your request for the removal of the EC2 e-mail sending limitations on your Amazon Web Services account. There are no longer limitations on your account for any IPs and instances under your account. If you requested removal of e-mail sending limits on Amazon Elastic IPs, they've also been removed.` gtg?

hello please help me to unblock the port 25, I have tried many times to do this but they rejected.
