### ISSUE TITLE
write and test an /etc/limits.conf

### ISSUE THREAD

**Issue by slingamn** [darwin-network/slash#9]
The ircd is currently affected by the default limit of 1024 open files. In theory, we should be able to support users up to the number of ephemeral ports available on the WAN interface (~10k)?

**Comment by eklitzke** [comment]
Why don't you just start by having oragono increase the soft limit = hard limit (4096 on nearly all linux distros).

**Comment by slingamn** [comment]
This was implemented with systemd's `LimitNOFILE` directive. We are now limited to about 500,000 clients.
